=== roza44/XML_Web_Servisi/Dokumenti/XML Seme/zalbacutanjecir.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:zlbc="http://www.ftn.uns.ac.rs/zalbacutanje"
    targetNamespace="http://www.ftn.uns.ac.rs/zalbacutanje" elementFormDefault="qualified">

    <xs:simpleType name="NazivType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="100"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="RazlogZalbeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Organ vlasti nije postupio u zakonskom roku"/>
            <xs:enumeration
                value="Organ vlasti nije postupio u celosti u zakonskom roku"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="Zalba">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Poverenik" type="zlbc:TPravno_lice"/>
                <xs:element name="Naziv_organa">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="zlbc:NazivType">
                                <xs:attribute name="property" type="xs:string"> </xs:attribute>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Razlog_zalbe">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="zlbc:RazlogZalbeType">
                                <xs:attribute name="property" type="xs:string"> </xs:attribute>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Trazene_informacije_o_zahtevu">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Datum_podnosenja">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:date">
                                            <xs:attribute name="property" type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Podaci_o_zahtevu_i_informacijama">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="property" type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Kopija_zahteva" type="xs:IDREF" minOccurs="0"/>
                <xs:element name="Kopija_odgovora_na_zahtev" type="xs:IDREF" minOccurs="0"/>
                <xs:element name="Datum_podnosenja_zalbe">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:date">
                                <xs:attribute name="property" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Podnosilac_zalbe">
                    <xs:complexType>
                        <xs:complexContent>
                            <xs:extension base="zlbc:TFizicko_lice">
                                <xs:sequence>
                                    <xs:element name="Ostali_kontakt_podaci" type="xs:string"/>
                                </xs:sequence>
                            </xs:extension>
                        </xs:complexContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="vocab" type="xs:string"/>
            <xs:attribute name="about" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Adresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Mesto">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="30"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element minOccurs="1" name="Postanski_broj">
                    <xs:simpleType>
                        <xs:restriction base="xs:int">
                            <xs:minInclusive value="11000"/>
                            <xs:maxInclusive value="40000"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Ulica" type="xs:string"/>
                <xs:element name="Broj">
                    <xs:simpleType>
                        <xs:restriction base="xs:int">
                            <xs:minInclusive value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType abstract="true" name="TLice">
        <xs:sequence>
            <xs:element ref="zlbc:Adresa"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPravno_lice">
        <xs:complexContent>
            <xs:extension base="zlbc:TLice">
                <xs:sequence>
                    <xs:element name="Naziv">
                        <xs:complexType>
                            <xs:simpleContent>
                                <xs:extension base="zlbc:NazivType">
                                    <xs:attribute name="property" type="xs:string"> </xs:attribute>
                                </xs:extension>
                            </xs:simpleContent>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TFizicko_lice">
        <xs:complexContent>
            <xs:extension base="zlbc:TLice">
                <xs:sequence>
                    <xs:element name="Ime">
                        <xs:complexType>
                            <xs:simpleContent>
                                <xs:extension base="zlbc:NazivType">
                                    <xs:attribute name="property" type="xs:string"> </xs:attribute>
                                </xs:extension>
                            </xs:simpleContent>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="Prezime">
                        <xs:complexType>
                            <xs:simpleContent>
                                <xs:extension base="zlbc:NazivType">
                                    <xs:attribute name="property" type="xs:string"> </xs:attribute>
                                </xs:extension>
                            </xs:simpleContent>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== roza44/XML_Web_Servisi/Dokumenti/XML Dokumenti/Ulaz/ZalbaNaCutanje1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Zalba xmlns="http://www.ftn.uns.ac.rs/zalbacutanje"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.ftn.uns.ac.rs/zalbacutanje file:/C:/Users/Luka/Documents/Workspace/XML%20i%20web%20servisi/XML_Web_Servisi/Dokumenti/XML%20Seme/zalbacutanjecir.xsd"
 xmlns:pred="http://examples/predicate/"
 vocab="http://examples/predicate/"
 about="http://ZalbaNaCutanje/1"
    >
    <Poverenik>
        <Adresa>
            <Mesto>Beograd</Mesto>
            <Postanski_broj>11000</Postanski_broj>
            <Ulica>Bulevar kralja Aleksandra</Ulica>
            <Broj>15</Broj>
        </Adresa>
        <Naziv>Poverenik za informacije od javnog znacaja i zastitu podataka o licnosti</Naziv>
    </Poverenik>
    <Naziv_organa property="pred:nazivOrgana">Ministarstvo finansija</Naziv_organa>
    <Razlog_zalbe property="pred:razlogZalbe">Organ vlasti nije postupio u zakonskom roku</Razlog_zalbe>
    <Trazene_informacije_o_zahtevu>
        <Datum_podnosenja property="pred:datumZahteva" >2020-01-03</Datum_podnosenja>
        <Podaci_o_zahtevu_i_informacijama property="pred:tekstZahteva" >Zahtevane su informacije o realizaciji budzeta drzave Srbije</Podaci_o_zahtevu_i_informacijama>
    </Trazene_informacije_o_zahtevu>
    <Datum_podnosenja_zalbe property="pred:datumZalbe">2020-05-04</Datum_podnosenja_zalbe>
    <Podnosilac_zalbe>
        <Adresa>
            <Mesto>Subotica</Mesto>
            <Postanski_broj>24000</Postanski_broj>
            <Ulica>Josipa Krasa</Ulica>
            <Broj>7</Broj>
        </Adresa>
        <Ime property="pred:imeGradjanina">Luka</Ime>
        <Prezime property="pred:prezimeGradjanina">Nikolic</Prezime>
        <Ostali_kontakt_podaci>kucni tel: 024/542-533</Ostali_kontakt_podaci>
    </Podnosilac_zalbe>
</Zalba>
